language: python
dist: trusty
install:
  - pip install -r requirements.txt
  - pip install -r optional-packages.txt
  - python setup.py install
script:
    - pytest
    - codecov
notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change
matrix:
  include:
  - os: linux
    python: 2.6
  - os: linux
    dist: xenial
    python: 2.7
  - os: linux
    dist: xenial
    python: 3.5
  - os: linux
    dist: xenial
    python: 3.6
  - os: linux
    dist: xenial
    python: 3.7
  - os: linux
    dist: xenial
    python: 3.8

