language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install chardet cchardet
install: "pip install -r requirements.txt"
script:
    - py.test --cov=lasio
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: change